services:
  web:
    build: "./web"
    ports:
      - "3000:3000"
    env_file:
      - ./config/env/.web_config.env
  users:
    build: "./users"
    ports:
      - "3003:3000"
    depends_on:
      - db
    env_file:
      - ./config/env/.users_config.env

  products:
    build: "./products"
    ports:
      - "3001:3000"
    depends_on:
      - db
    env_file:
      - ./config/env/.products_config.env

  auth:
    build: "./auth"
    ports:
      - "3002:3000"
    depends_on:
      - db
    env_file:
      - ./config/env/.auth_config.env

  db:
    image: mongo
    ports:
      - "27017:27017"
  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./web/public:/srv/www/static
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
      - users
      - products
      - auth
