version: '3'
services:
  app:
    container_name: "Market-Place-product"
    restart: always
    build: .
    ports:
      - '80:3001'
    external_links:
      - mongo
    env_file:
      - ./.env
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
